In [9]:
import csv

titulo = input("Por favor, inserte aquí el título de la película serie o saga: ")
year = input("Por favor, inserte aquí el año: ")
categoria = input ("Por favor, elija una de las categorías:\n A) COMEDIES\n B) INTRIGUE\n C) ACTION\n D) THRILLER\n E) ROMANTIC\n F) SAGAS AND SERIES\n G)FINANCE\n \nELIGE A, B, C, D, E, F o G.\n")
movie_nueva = []

while categoria not in ["A", "B", "C", "D", "E", "F", "G"]:
    print("Esta opción no es válida, por favor, prueba otra vez.")
    categoria = input ("Por favor, elija una de las categorías:\n A) COMEDIES\n B) INTRIGUE\n C) ACTION\n D) THRILLER\n E) ROMANTIC\n F) SAGAS AND SERIES\n G)FINANCE\n \nELIGE A, B, C, D, E, F o G.\n")
else:
    if (categoria == "A"):
        movie_nueva.append("COMEDIES")
    elif (categoria == "B"):
        movie_nueva.append("INTRIGUE")
    elif (categoria == "C"):
        movie_nueva.append("ACTION")
    elif (categoria == "D"):
        movie_nueva.append("THRILLER")
    elif (categoria == "E"):
        movie_nueva.append("ROMANTIC")
    elif (categoria == "F"):
        movie_nueva.append("SAGAS AND SERIES")
    else:
        movie_nueva.append("FINANCE")
    movie_nueva.append(titulo)
    movie_nueva.append(int(year))
    print(movie_nueva)
    
    # Abre el archivo CSV en modo de "append" ('a') para añadir sin sobrescribir
    with open('generadorBBDD/Movies_DEF.csv', mode='a', newline='') as archivo:
        writer = csv.writer(archivo)

        # Escribe la nueva fila en el archivo
        writer.writerow(movie_nueva)

Por favor, inserte aquí el título de la película serie o saga: La gata sobre el tejado de Zinc
Por favor, inserte aquí el año: 1958
Por favor, elija una de las categorías:
 A) COMEDIES
 B) INTRIGUE
 C) ACTION
 D) THRILLER
 E) ROMANTIC
 F) SAGAS AND SERIES
 G)FINANCE

ELIGE A, B, C, D, E, F o G.
E
['ROMANTIC', 'La gata sobre el tejado de Zinc', 1958]

In [10]:
import pandas as pd
df_def = pd.read_csv("generadorBBDD/Movies_DEF.csv", encoding='ISO-8859-1')
df_def

             Category                  Movie or Series  Year
0            COMEDIES     Guess Who's Coming to Dinner  1967
1            COMEDIES                  What's Up, Doc?  1972
2    SAGAS AND SERIES           Guerra de las galaxias  1977
3             FINANCE                   Trading places  1983
4             FINANCE                      Wall Street  1987
..                ...                              ...   ...
122          COMEDIES        Hitman's Wife's Bodyguard  2021
123          INTRIGUE                      Glass Onion  2023
124          COMEDIES                 No hard feelings  2023
125          COMEDIES                 Murder Mystery 2  2023
126          ROMANTIC  La gata sobre el tejado de Zinc  1958

[127 rows x 3 columns]

In [11]:
# Sort the dataset by the "Year" column in ascending order, placing NaN values at the end
df_sorted = df_def.sort_values("Year", ascending=True)
df_sorted.to_csv("generadorBBDD/Movies_DEF.csv", index=False)

In [12]:
movies_DEF = pd.read_csv("generadorBBDD/Movies_DEF.csv", encoding='ISO-8859-1')
print(movies_DEF) #ESTE ES CON EL QUE NOS VAMOS QUEDANDO

             Category                  Movie or Series  Year
0            ROMANTIC  La gata sobre el tejado de Zinc  1958
1            COMEDIES     Guess Who's Coming to Dinner  1967
2            COMEDIES                  What's Up, Doc?  1972
3    SAGAS AND SERIES           Guerra de las galaxias  1977
4             FINANCE                   Trading places  1983
..                ...                              ...   ...
122  SAGAS AND SERIES               The queen's gambit  2020
123          COMEDIES        Hitman's Wife's Bodyguard  2021
124          INTRIGUE                      Glass Onion  2023
125          COMEDIES                 No hard feelings  2023
126          COMEDIES                 Murder Mystery 2  2023

[127 rows x 3 columns]